# Generated by Django 3.1.4 on 2021-01-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('status', models.TextField(max_length=3)),
                ('registrationCharge', models.IntegerField()),
                ('registrationTax', models.IntegerField()),
                ('registrationTotal', models.IntegerField()),
                ('fileUpload', models.URLField()),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byname', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
                ('vidio_url', models.URLField(max_length=500)),
                ('comment', models.TextField(max_length=4000)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Supportedby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofthecompany', models.CharField(max_length=100)),
                ('imgurl', models.ImageField(upload_to='')),
                ('Event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
                ('fb_link', models.URLField(max_length=500)),
                ('twitter_link', models.URLField(max_length=500)),
                ('description', models.TextField(max_length=4000)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='our_partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Media_Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField(max_length=500)),
                ('link', models.URLField(max_length=500)),
                ('event', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycle_app.event')),
            ],
        ),
    ]
