# Generated by Django 3.1.4 on 2021-01-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportedby',
            old_name='Event',
            new_name='eveid',
        ),
    ]
